# Generated by Django 3.2.5 on 2021-07-29 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TransactionsBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsbook',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionsbook',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionsbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
