# Generated by Django 3.2.5 on 2021-08-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
        ('TransactionsBook', '0002_auto_20210729_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsbook',
            name='transactions',
            field=models.ManyToManyField(to='Transaction.Transaction'),
        ),
    ]
