# Generated by Django 4.1.5 on 2023-02-17 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExpenseRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='users',
            field=models.ManyToManyField(related_name='expense_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
