# Generated by Django 4.1.5 on 2023-04-11 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExpenseRecord', '0002_expenserecord_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la dépense')),
                ('amount', models.CharField(max_length=255, verbose_name='Montant de la dépense')),
                ('date', models.CharField(max_length=255, verbose_name='Date de la dépense')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la dépense')),
                ('expense_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='ExpenseRecord.expenserecord')),
            ],
        ),
    ]
